// Private receipt storage. Receipts are never placed in a public directory or bucket.

export type StorageDriver = 'local' | 's3';

export type DownloadTarget =
  | { kind: 'bytes'; data: Uint8Array; contentType: string; filename: string }
  | { kind: 'redirect'; url: string; expiresInSeconds: number };

export interface ReceiptStorage {
  readonly driver: StorageDriver;
  put(key: string, data: Uint8Array, contentType: string): Promise<void>;
  remove(key: string): Promise<void>;
  open(key: string, options: { filename: string; contentType: string }): Promise<DownloadTarget>;
}

/** Storage keys are generated by the server. Anything else is rejected before touching the filesystem or bucket. */
export const STORAGE_KEY_PATTERN = /^receipts\/\d{4}\/[0-9a-f-]{36}\/[0-9a-f-]{36}\.(pdf|jpg|png)$/;

export function assertStorageKey(key: string): void {
  if (!STORAGE_KEY_PATTERN.test(key) || key.includes('..')) {
    throw new Error('Refusing to use an unexpected storage key.');
  }
}

/** Keeps only safe characters in download filenames and strips path components. */
export function safeDownloadName(name: string, extension: string): string {
  const base = name.split(/[\\/]/).pop() ?? 'receipt';
  const cleaned = base.replace(/[^A-Za-z0-9._ -]/g, '_').replace(/\s+/g, ' ').trim().slice(0, 120);
  const stem = cleaned.replace(/\.[A-Za-z0-9]{1,6}$/, '') || 'receipt';
  return `${stem}.${extension}`;
}
